# Generated by Django 4.2.7 on 2024-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=100)),
                ("product_desc", models.TextField(max_length=100)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_category", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
